# Generated by Django 5.2.7 on 2025-10-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorythreshold',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storefront.product'),
        ),
    ]
