# Generated by Django 5.2.6 on 2025-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category_customer_product_stockhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_category',
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income_sgd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
