# Generated by Django 5.2.7 on 2025-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_alter_customer_username_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='monthly_income_sgd',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
