# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_customer_monthly_income_sgd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='income_range',
        ),
    ]
